name: Generate Keystore (One-Time)

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -storetype PKCS12 \
            -keystore upload-keystore.jks \
            -alias my-key-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass your_strong_password \
            -keypass your_strong_password \
            -dname "CN=TimeDirector, OU=Engineering, O=TimeDirector, L=Paris, S=IDF, C=FR"

      - name: Get Base64 String
        run: |
          echo "::warning::COPY THE BELOW STRING FOR GITHUB SECRET 'ANDROID_KEYSTORE_BASE64'"
          echo "----------------------------------------------------------------"
          base64 -w 0 upload-keystore.jks
          echo ""
          echo "----------------------------------------------------------------"

      - name: Upload Keystore
        uses: actions/upload-artifact@v3
        with:
          name: upload-keystore
          path: upload-keystore.jks
